#!/bin/sh

# Copyright 2018 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Notes:
#  - Please install "jq" package before using this driver.

usage() {
  err "Invalid usage. Usage: "
  err "\t$0 init"
  err "\t$0 mountdevice <mount dir> <mount device> <json params>"
  err "\t$0 unmountdevice <mount dir>"
  exit 1
}

err() {
  echo $* 1>&2
}

log() {
  echo $* >&1
}

domount() {
  mntPath=$1
  node=$(echo $2 | jq -r '.node')
  export_id=$(echo $2 | jq -r '.export_id')
  mmpUpdateInterval=$(echo $3 | jq -r '.mmpUpdateInterval')

  [ null = "${mmpUpdateInterval}" ] && mmpUpdateInterval=5
  [ null = "${fsckOptions}"       ] && fsckOptions="a"

  if [ -n "${mmpUpdateInterval}" ]; then
    mmpOptions="-O mmp -E mmp_update_interval=${mmpUpdateInterval}"
  fi
  
  bindPath="/mnt/rozofs@${node}/export_${export_id}"
  
  if ! mountpoint -q "${bindPath}";then
    err "{ \"status\": \"Failure\", \"message\": \"Rozofs mountpoint not available\"}"
    exit 1
  fi

  if mountpoint -q "${mntPath}"; then
    log "{\"status\": \"Success\"}"
    exit 0
  fi

  mkdir -p "${mntPath}" &> /dev/null

  mount --bind  ${bindPath} ${mntPath} &> /dev/null
  if [ $? -ne 0 ]; then
    err "{ \"status\": \"Failure\", \"message\": \"Failed to mount rozofs from node ${node} at ${mntPath}\"}"
    exit 1
  fi

  log "{\"status\": \"Success\"}"
  exit 0
}

unmount() {
  mntPath=$1
  if [ -d ${mntPath} ] && mountpoint -q "${mntPath}"; then
    umount ${mntPath} &> /dev/null
    if [ $? -ne 0 ]; then
      err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${mntPath}\"}"
      exit 1
    fi
  fi
  log "{\"status\": \"Success\"}"
  exit 0
}

op=$1

echo $@ >> /tmp/123

if ! command -v jq >/dev/null 2>&1; then
  err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
  exit 1
fi

if [ "$op" = "init" ]; then
  log '{"status": "Success", "capabilities": {"attach": false}}'
  exit 0
fi

if [ $# -lt 2 ]; then
  usage
fi

shift

case "$op" in
  mount)
    domount $*
    ;;
  unmount)
    unmount $*
    ;;
  *)
    log "{ \"status\": \"Not supported\" }"
    exit 0
    ;;
esac

exit 1
