kind: Deployment
apiVersion: apps/v1
metadata:
  name: rozofs-provisioner
  labels:
    app: rozofs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rozofs-provisioner
  template:
    metadata:
      labels:
        app: rozofs-provisioner
    spec:
      hostNetwork: true
      serviceAccountName: rozofs
      containers:
        - name: rozofs-provisioner
          image: mochacoffee/rozofs-provision:latest
          imagePullPolicy: "Always"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ROZO_EXPORT_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: rozofs-cluster
                  key: exportnode
            - name: CLUSTER_NODES
              valueFrom:
                configMapKeyRef:
                  name: rozofs-cluster
                  key: clusternodes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rozofs
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rozofs
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rozofs
subjects:
  - kind: ServiceAccount
    name: rozofs
    namespace: default
roleRef:
  kind: ClusterRole
  name: rozofs
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-rozofs
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["list", "watch", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-rozofs
subjects:
  - kind: ServiceAccount
    name: rozofs
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-rozofs
  apiGroup: rbac.authorization.k8s.io
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rozofs
provisioner: mochacoffee/rozofs
reclaimPolicy: Delete
