kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: nginx
    volumeMounts:
      - name: vol
        mountPath: "/data"
  restartPolicy: "Always"
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: rozofs-pvc
