kind: Deployment
apiVersion: apps/v1
metadata:
  name: rozofs-provisioner
  labels:
    app: rozofs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rozofs-provisioner
  template:
    metadata:
      labels:
        app: rozofs-provisioner
    spec:
      hostNetwork: true
      serviceAccountName: rozofs
      containers:
        - name: rozofs-provisioner
          image: mushroommagnet/rozofs-provision:latest
          imagePullPolicy: "Always"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ROZO_EXPORT_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rozofs-secret
                  key: exportnode
            - name: CLUSTER_NODES
              valueFrom:
                secretKeyRef:
                  name: rozofs-secret
                  key: clusternodes
